# Generated by Django 4.1.3 on 2022-11-09 20:02
# TODO Generiert ein paar Sprachen beim Migrieren, damit wir was in der Datenbank haben
# Die languages.txt muss noch aufgefüllt werden, aber fürs erste ist es wohl besser, da 
# nur eine handvoll Sprachen zur Auswahl zu haben

from django.db import migrations


def load_languages(apps, schema_editor):
    Sprache = apps.get_model('betreiber', 'Sprache')
    with open('languages.txt', encoding='utf8') as file:
        
        languages = file.read().split('\n')

        for line in languages:
            if (not line):
                continue
            name, code = line.split(',')
            sprache = Sprache(name=name, code=code, flag='')
            sprache.save()


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_languages)
    ]
