# Generated by Django 4.1.3 on 2022-11-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0002_auto_20221109_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
        migrations.AlterField(
            model_name='mandant',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verwalter', to=settings.AUTH_USER_MODEL),
        ),
    ]
