# Generated by Django 4.1.3 on 2022-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0003_group_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seite',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
