# Generated by Django 4.1.3 on 2022-12-11 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0004_alter_seite_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
