# Generated by Django 4.1.3 on 2022-11-22 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0004_alter_autor_options_alter_buch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandant',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='verwaltet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seiten', to='betreiber.buch'),
        ),
        migrations.AddConstraint(
            model_name='seite',
            constraint=models.UniqueConstraint(fields=('seitenzahl', 'book'), name='SpezifischeSeite'),
        ),
    ]
