# Generated by Django 4.1.3 on 2022-11-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0006_alter_seite_options_mandant_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivierungscode',
            name='mandant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_codes', to='betreiber.mandant'),
        ),
    ]
