# Generated by Django 4.1.3 on 2022-11-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0007_alter_aktivierungscode_mandant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einladung',
            name='code',
            field=models.UUIDField(unique=True),
        ),
    ]
