# Generated by Django 4.1.3 on 2022-11-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0008_alter_einladung_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aktivierungscode',
            constraint=models.UniqueConstraint(fields=('mandant', 'book'), name='BuchPerMandant'),
        ),
    ]
