# Generated by Django 4.1.3 on 2022-11-28 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0009_aktivierungscode_buchpermandant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprachaufnahme',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufnahmen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sprache',
            name='users',
            field=models.ManyToManyField(related_name='sprachen', to=settings.AUTH_USER_MODEL),
        ),
    ]
