# Generated by Django 4.1.3 on 2022-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0010_alter_sprachaufnahme_recorded_by_alter_sprache_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprache',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='sprachen',
            field=models.ManyToManyField(related_name='users', to='betreiber.sprache'),
        ),
    ]
